### ISSUE TITLE
Add a name to callback

### ISSUE THREAD

**Issue by eorroe** [daguej/sublime-insertcallback#1]
When inserting the callback the arguments are selected first, could the name of the function be selected first then the arguments, and then the function body?

fn name -> fn args -> fn body

**Comment by daguej** [comment]
Named callbacks added as <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>.

**Comment by eorroe** [comment]
Is there a key command for this? I'd like to change the keybinding:

``` JSON
{ "keys": ["alt+c"], "command": "INEEDTHIS" }
```

**Comment by eorroe** [comment]
NVM found it in the code thanks!
